"""empty message

Revision ID: 881d3f90f25d
Revises: eda66d588b7f
Create Date: 2021-10-24 01:29:06.551434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881d3f90f25d'
down_revision = 'eda66d588b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_booking_booking_id'), 'booking', ['booking_id'], unique=False)
    op.drop_column('booking', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('end_time', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_booking_booking_id'), table_name='booking')
    op.drop_column('booking', 'end_date')
    # ### end Alembic commands ###
