"""empty message

Revision ID: e05b5a6b7329
Revises: 
Create Date: 2021-10-23 19:31:47.613368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05b5a6b7329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.Column('bike_brand', sa.String(length=64), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bike_id')
    )
    op.create_index(op.f('ix_bike_bike_id'), 'bike', ['bike_id'], unique=False)
    op.create_table('bike__availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike__availability_location'), 'bike__availability', ['location'], unique=False)
    op.create_table('bike__location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_Serial_no', sa.String(length=64), nullable=True),
    sa.Column('current_location', sa.String(length=128), nullable=True),
    sa.Column('previous_location', sa.String(length=128), nullable=True),
    sa.Column('current_location_latlong', sa.String(length=128), nullable=True),
    sa.Column('previous_location_latlong', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike__location_bike_Serial_no'), 'bike__location', ['bike_Serial_no'], unique=True)
    op.create_index(op.f('ix_bike__location_current_location'), 'bike__location', ['current_location'], unique=False)
    op.create_index(op.f('ix_bike__location_current_location_latlong'), 'bike__location', ['current_location_latlong'], unique=False)
    op.create_index(op.f('ix_bike__location_previous_location'), 'bike__location', ['previous_location'], unique=False)
    op.create_index(op.f('ix_bike__location_previous_location_latlong'), 'bike__location', ['previous_location_latlong'], unique=False)
    op.create_table('bike__parking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_Serial_no', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('Parking_Status', sa.Boolean(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike__parking_id'), 'bike__parking', ['id'], unique=False)
    op.create_table('bike__status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_Serial_no', sa.Integer(), nullable=True),
    sa.Column('rent_status', sa.Boolean(), nullable=True),
    sa.Column('defective_status', sa.Boolean(), nullable=True),
    sa.Column('lock_status', sa.Boolean(), nullable=True),
    sa.Column('parked_status', sa.Boolean(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike__status_id'), 'bike__status', ['id'], unique=False)
    op.create_table('bike_repair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.Column('reported_date', sa.DateTime(), nullable=True),
    sa.Column('fixed_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'bike_id')
    )
    op.create_index(op.f('ix_bike_repair_bike_id'), 'bike_repair', ['bike_id'], unique=False)
    op.create_index(op.f('ix_bike_repair_id'), 'bike_repair', ['id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('start_location', sa.String(length=100), nullable=True),
    sa.Column('end_location', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=100), nullable=True),
    sa.Column('booking_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_booking_id'), 'feedback', ['booking_id'], unique=True)
    op.create_index(op.f('ix_feedback_customer_id'), 'feedback', ['customer_id'], unique=True)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('payment_by', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_booking_id'), 'payment', ['booking_id'], unique=True)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phonenumber', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phonenumber'), 'users', ['phonenumber'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phonenumber'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_booking_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_customer_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_booking_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_bike_repair_id'), table_name='bike_repair')
    op.drop_index(op.f('ix_bike_repair_bike_id'), table_name='bike_repair')
    op.drop_table('bike_repair')
    op.drop_index(op.f('ix_bike__status_id'), table_name='bike__status')
    op.drop_table('bike__status')
    op.drop_index(op.f('ix_bike__parking_id'), table_name='bike__parking')
    op.drop_table('bike__parking')
    op.drop_index(op.f('ix_bike__location_previous_location_latlong'), table_name='bike__location')
    op.drop_index(op.f('ix_bike__location_previous_location'), table_name='bike__location')
    op.drop_index(op.f('ix_bike__location_current_location_latlong'), table_name='bike__location')
    op.drop_index(op.f('ix_bike__location_current_location'), table_name='bike__location')
    op.drop_index(op.f('ix_bike__location_bike_Serial_no'), table_name='bike__location')
    op.drop_table('bike__location')
    op.drop_index(op.f('ix_bike__availability_location'), table_name='bike__availability')
    op.drop_table('bike__availability')
    op.drop_index(op.f('ix_bike_bike_id'), table_name='bike')
    op.drop_table('bike')
    # ### end Alembic commands ###
