"""empty message

Revision ID: eda66d588b7f
Revises: e05b5a6b7329
Create Date: 2021-10-23 19:56:12.950697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda66d588b7f'
down_revision = 'e05b5a6b7329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike__availability', sa.Column('current_location_latlong', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_bike__availability_current_location_latlong'), 'bike__availability', ['current_location_latlong'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bike__availability_current_location_latlong'), table_name='bike__availability')
    op.drop_column('bike__availability', 'current_location_latlong')
    # ### end Alembic commands ###
